image:
  name: registry.gitlab.com/consensus.enterprises/drumkit/ddev
  entrypoint: [""] # We have to override the container entrypoint or else we end up in /bin/sh and `. d` doesn't work. See https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#overriding-the-entrypoint-of-an-image

stages:
  - test
  - publish

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DEBIAN_FRONTEND: noninteractive

tests:
  stage: test
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    FF_NETWORK_PER_BUILD: 'true' # Allow service containers to see each other; see https://docs.gitlab.com/ee/ci/services/#connecting-services
    DEBIAN_FRONTEND: noninteractive
  services:
    - name: docker:20-dind
      alias: docker
      command: ["--tls=false"]
  script:
    # We must chown the code in our own home dir because we still, after many years, cannot stop Gitlab CI from checking it out as root. See: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/2750
    - sudo chown -R ddev:ddev .
    - ddev config global --instrumentation-opt-in=true
    - ddev mutagen reset && ddev config global --mutagen-enabled=false
    - ddev start
    - ddev composer install
    - ddev behat

#fast-tests: &test-defaults
#  stage: test
#  script:
#    - source d
#    - make clean-ansible  # Clean up Ansible config from Drumkit itself.
#    - make run-behat-ci
#
#slow-tests:
#  <<: *test-defaults
#  variables:
#    BEHAT_CI_TAGS: '@slow&&~@wip'
#
## This test will fail (on purpose), in order to test that failure notifications are sent.
#noisy-tests:
#  <<: *test-defaults
#  variables:
#    NOTIFY_CI_MESSAGE: Notification test; safe to ignore failures.
#  script:
#    - source d
#    - BEHAT_CI_TAGS=success make run-behat-ci
#    - BEHAT_CI_TAGS=failure make run-behat-ci
#  when: manual
#  allow_failure: true

pages:
  stage: publish
  image: registry.gitlab.com/pages/hugo:latest
  before_script:
    # Check the current version of Hugo, so we can keep our local env in sync.
    - hugo version
  script:
    # Build our docs site.
    - cd docs && hugo && mv public/ ..
  artifacts:
    paths:
      - public
  only:
    - master

