image: registry.gitlab.com/pages/hugo:latest

stages:
  - test
  - publish

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  BEHAT_OPTS: --stop-on-failure --colors

fast-tests: &test-defaults
  stage: test
  image: php:7.2
  before_script:
    # Install Git and GNU Make
    - apt-get update -yqq
    - apt-get install -yqq git make python-pip unzip
    - pip install jinja2-cli PyYAML ntfy[matrix]
    - make behat
    - source d
  script:
    - behat $BEHAT_OPTS
    - RESULT=$? make ntfy-ci

slow-tests:
  <<: *test-defaults
  script:
    - behat $BEHAT_OPTS --tags=slow
    - RESULT=$? make ntfy-ci

pages:
  stage: publish
  before_script:
    # Check the current version of Hugo, so we can keep our local env in sync.
    - hugo version
  script:
    # Build our site.
    - cd docs && hugo && mv public/ ..
  artifacts:
    paths:
      - public
  only:
    - master

