image: registry.gitlab.com/pages/hugo:latest

stages:
  - test
  - publish

variables:
  GIT_SUBMODULE_STRATEGY: recursive

fast-tests: &test-defaults
  stage: test
  image: php:7.2
  before_script:
    # Install Git and GNU Make
    - apt-get update -yqq
    - apt-get install -yqq git make
    - make behat
  script:
    - behat

slow-tests:
  <<: *test-defaults
  script:
    - behat --tags=slow

pages:
  stage: publish
  before_script:
    # Check the current version of Hugo, so we can keep our local env in sync.
    - hugo version
  script:
    # Build our site.
    - cd docs && hugo && mv public/ ..
  artifacts:
    paths:
      - public
  only:
    - master

