image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  stage: deploy
  before_script:
    # Check the current version of Hugo, so we can keep our local env in sync.
    - hugo version
    # Install GNU Make
    - apk add --update make bash
  script:
    # Build our site.
    - hugo
  artifacts:
    paths:
      - public
  only:
    - master

