image: registry.gitlab.com/pages/hugo:latest

stages:
  - test
  - publish

variables:
  GIT_SUBMODULE_STRATEGY: recursive

fast-tests: &test-defaults
  stage: test
  image: php:7.2
  before_script:
    # Install Git and GNU Make
    - apt-get update -yqq
    - apt-get install -yqq git make
    # TODO: Figure out a way to intall these system packages as dependecies of
    # the targets that use them.
    # TODO: Inital ansible run requires python (not python3). How to fix?
    - apt-get install -yqq python-minimal python3-minimal python3-pip unzip
    - pip3 install jinja2-cli PyYAML ntfy[matrix] ansible
  script:
    - source d
    - make run-behat-ci

slow-tests:
  <<: *test-defaults
  variables:
    BEHAT_CI_TAGS: slow

# This test will fail (on purpose), in order to test that failure notifications are sent.
noisy-tests:
  <<: *test-defaults
  variables:
    NOTIFY_CI_MESSAGE: Notification test; safe to ignore failures.
  script:
    - source d
    - BEHAT_CI_TAGS=success make run-behat-ci
    - BEHAT_CI_TAGS=failure make run-behat-ci
  when: manual
  allow_failure: true

pages:
  stage: publish
  before_script:
    # Check the current version of Hugo, so we can keep our local env in sync.
    - hugo version
  script:
    # Build our docs site.
    - cd docs && hugo && mv public/ ..
  artifacts:
    paths:
      - public
  only:
    - master

