image: registry.gitlab.com/pages/hugo:latest

stages:
  - test
  - publish

variables:
  GIT_SUBMODULE_STRATEGY: recursive

fast-tests: &test-defaults
  stage: test
  image: php:7.2
  before_script:
    # Install Git and GNU Make
    - apt-get update -yqq
    - apt-get install -yqq git make
    # TODO: Figure out a way to intall these system packages as dependecies of
    # the targets that use them.
    - apt-get install -yqq python-pip unzip
    - pip install jinja2-cli PyYAML ntfy[matrix]
  script:
    - source d
    - make run-behat-ci

slow-tests:
  <<: *test-defaults
  vars:
    BEHAT_TAGS: slow

# This test will fail (on purpose), in order to test that failure notifications are sent.
noisy-tests:
  <<: *test-defaults
  script:
    - source d
    - BEHAT_TAGS=success make run-behat-ci
    - BEHAT_TAGS=failure make run-behat-ci
  when: manual
  allow_failure: true

pages:
  stage: publish
  before_script:
    # Check the current version of Hugo, so we can keep our local env in sync.
    - hugo version
  script:
    # Build our docs site.
    - cd docs && hugo && mv public/ ..
  artifacts:
    paths:
      - public
  only:
    - master

