---
- name: Send matrix notification via Ansible.
  hosts: localhost
  gather_facts: False

  tasks:

    - name: Ensure that Matrix client dependency is installed.
      pip:
        name: matrix-client
        extra_args: --user

    - name: Send matrix notification.
      matrix:
        msg_plain: ''
        msg_html: "{{ matrix_msg }}"
        room_id: "{{ matrix_room_id }}"
        hs_url: "{{ matrix_hs_url }}"
        token: "{{ matrix_auth_token }}"

