Feature: Generate Ansible config
  In order to initialize an Ansible project
  As a DevOps engineer
  I want to specify a server and a group and have Ansible config auto-generated for them.

   @ansible @ansible-config
   Scenario: Generate Ansible config
    Given I bootstrap Drumkit
      And I run "git init"
      And I run "make generate-ansible-config host=myhost group=mygroup"
      Then I should get:
      """
      Generating Ansible config files
      """
      Then the following files should exist:
      """
      inventory/host_vars/myhost.yml
      inventory/group_vars/mygroup.yml
      playbooks/hosts/myhost.yml
      playbooks/groups/mygroup.yml
      """
      And the file "inventory/host_vars/myhost.yml" should contain:
      """
      Host vars file generated by Drumkit; place variables that are specific to the `myhost` host here.
      """
      And the file "inventory/group_vars/mygroup.yml" should contain:
      """
      Group vars file generated by Drumkit; place variables that are specific to the `mygroup` group here.
      """
      And the file "playbooks/hosts/myhost.yml" should contain:
      """
      - name: Host playbook for host 'myhost' generated by Drumkit.
        hosts: myhost
        become: true
        gather_facts: True
      """
      And the file "playbooks/groups/mygroup.yml" should contain:
      """
      - name: Group playbook for group 'mygroup' generated by Drumkit.
        hosts: mygroup
      """

   @ansible @ansible-config
   Scenario: Generate example Ansible config by default
    Given I bootstrap Drumkit
      And I run "git init"
      And I run "make generate-ansible-config"
      Then I should get:
      """
      Generating Ansible config files
      """
      Then the following files should exist:
      """
      inventory/host_vars/example-host.yml
      inventory/group_vars/example_group.yml
      playbooks/hosts/example-host.yml
      playbooks/groups/example_group.yml
      """
      And the file "inventory/host_vars/example-host.yml" should contain:
      """
      Host vars file generated by Drumkit; place variables that are specific to the `example-host` host here.
      """
      And the file "inventory/group_vars/example_group.yml" should contain:
      """
      Group vars file generated by Drumkit; place variables that are specific to the `example_group` group here.
      """
      And the file "playbooks/hosts/example-host.yml" should contain:
      """
      - name: Host playbook for host 'example-host' generated by Drumkit.
        hosts: example-host
        become: true
        gather_facts: True
      """
      And the file "playbooks/groups/example_group.yml" should contain:
      """
      - name: Group playbook for group 'example_group' generated by Drumkit.
        hosts: example_group
      """
