baseURL: "https://drumk.it"
title: Makefiles everywhere!
languageCode: "en-us"
theme: "harmony"
params:
  editURL: "https://gitlab.com/-/ide/project/consensus.enterprises/drumkit/edit/master/-/content/"
