@init @aegirvps @project
Feature: Initialize AegirVPS projects.
  In order to use deploy and configure AegirVPS systems
  As a DevOps engineer
  I need to be able to initialize AegirVPS projects

   @wip
   Scenario: Initialize an AegirVPS project
     Given I bootstrap Drumkit
      When I run "make init-project-aegirvps"
      Then I should get:
       """
       Initializing Drumkit AegirVPS project
       Finished initializing Drumkit AegirVPS project
       """
       And the following files should not exist:
       """
       inventory/group_vars/example_group.yml
       inventory/host_vars/example-host.yml
       playbooks/groups/example_group.yml
       playbooks/hosts/example-host.yml
       """
       And the following files should exist:
       """
       inventory/group_vars/aegir.yml
       inventory/host_vars/aegir0.yml
       inventory/host_vars/localhost.yml
       playbooks/groups/aegir.yml
       playbooks/hosts/aegir0.yml
       playbooks/infra.yml
       """
       #inventory/host_vars/all.yml
       And the file "inventory/group_vars/aegir.yml" should contain:
       """
       Group vars file generated by Drumkit; place variables that are specific to the `aegir` group here.
       """
       #And the file "playbooks/groups/aegir.yml" should contain: 
       #"""
       #---
       #- name: Group playbook for group 'aegir' generated by Drumkit.
       #  hosts: aegir
       #
       #  roles:
       #    - consensus.admin-users
       #    - consensus.aegir-policy
       #"""
       And the file "inventory/host_vars/aegir0.yml" should contain:
       """
       Host vars file generated by Drumkit; place variables that are specific to the `aegir0` host here.
       """
       #And the file "playbooks/host_vars/all.yml" should contain:
       #"""
       #admin_users:
       #  - name: ergonlogic
       #  - name: lamech
       #  - name: spiderman
       #  - name: colan
       #"""
       #And the file "playbooks/host_vars/localhost.yml" should contain:
       #"""
       #os_servers:
       #  - name: 'aegir0'
       #    groups:
       #      - aegir
       #"""
       And the file "playbooks/hosts/aegir0.yml" should contain:
       """
       ---
       - name: Host playbook for host 'aegir0' generated by Drumkit.
         hosts: aegir0
       """
       #And the file "playbooks/infra.yml" should contain:
       #"""
       #---
       #- name: Provision Openstack cloud infrastructure
       #  hosts: localhost
       #
       #  roles:
       #    - consensus.cloud-openstack
       #"""

